# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k1gJeKC_WZWCP9R-h_eNYWi8mk0vKDQB
"""

import streamlit as st
import pandas as pd

df = pd.read_csv('Police_Department_Incident_Reports__2018_to_Present.csv')

st.markdown('https://drive.google.com/file/d/1gn1R8VW18VI3tUMG2MCwr_LbDaI1SmcE/view?usp=sharing')

mapa=pd.DataFrame()
mapa=mapa.dropna()
st.map(mapa.astype(int))